name: Android Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - uses: android-actions/setup-android@v3

      - run: npm ci
      - run: npx ionic build
      - run: npx cap sync android

      - name: Prepare keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > android/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build AAB
        working-directory: android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          echo "
          MYAPP_UPLOAD_STORE_FILE=keystore.jks
          MYAPP_UPLOAD_KEY_ALIAS=$KEY_ALIAS
          MYAPP_UPLOAD_STORE_PASSWORD=$KEYSTORE_PASSWORD
          MYAPP_UPLOAD_KEY_PASSWORD=$KEY_PASSWORD
          " >> gradle.properties
          ./gradlew clean bundleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/*.aab
